using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
namespace nicorankLib.SnapShot
{

    public class SnapShotJson
    {
        [JsonProperty("meta")]
        public MetaJson Meta { get; set; }

        [JsonProperty("data")]
        public List<SnapShotJsonData> Data { get; set; }


        public static SnapShotJson FromJson(string json)
        {
            return JsonConvert.DeserializeObject<SnapShotJson>(json);
        }

        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
        public class SnapShotJsonData
        {
            [JsonProperty("contentId")]
            public string ID { get; set; }

            [JsonProperty("commentCounter")]
            public long CountComment { get; set; }

            [JsonProperty("viewCounter")]
            public long CountPlay { get; set; }

            [JsonProperty("mylistCounter")]
            public long CountMylist { get; set; }

            [JsonProperty("likeCounter")]
            public long CountLike { get; set; }
        }

        public class MetaJson
        {
            [JsonProperty("status")]
            public long Status { get; set; }

            [JsonProperty("totalCount")]
            public long TotalCount { get; set; }

            [JsonProperty("id")]
            public Guid Id { get; set; }
        }
    }


}
